org: srinivas8919
app: aws-python-flask-api-project
service: aws-python-flask-api-project

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  environment:
    MONGO_URI: mongodb+srv://Srinivas:Srinivas%40123@cluster0.zmgm0e1.mongodb.net/
  memorySize: 128
  timeout: 15

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
